//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zhou.Services.RepositoryImpl
{
    using zhou.Models.DBModels;
    using zhou.Services.Repository;
    
    
    public class MenuRepository : BaseRepository<Menu>, IMenuRepository
    {
        
        public MenuRepository(IUnitOfWork uow) : 
                base(uow)
        {
        }
    }
}
